server:
  port: 8081
  servlet:
    session:
      timeout: 86400
    encoding:
      charset: UTF-8


spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 700MB
      max-request-size: 700MB
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

