server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8


spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
